### PR TITLE
Fixes for nested types

### PR DESCRIPTION
**Pull request by acecilia**
Solves https://github.com/eneko/SourceDocs/issues/50

Also, some other changes:
* Fixed typealias doc generation
* Added option `reproducibleDocs` in order to be able to generate reproducible documentation
* Added checks on CI for docs and linux tests

### CODE REVIEW

**Comment by acecilia** [comment]
@eneko would it be possible to get a release with this? 👯

**Comment by eneko** [comment]
Yes, sure thing. I’d like to update the README file and CHANGELOG, hopefully I can do it soon.

**Comment by eneko** [comment]
@acecilia are you on Twitter? Couldn't find your account

**Comment by acecilia** [comment]
Nope :/

**Pull request merged**
