### PR TITLE
Option to skip elements with no comments

### PR DESCRIPTION
**Pull request by Fiser33**
Hello, I'm trying to use your tool on large project. Generating documentation for all files makes it rather not usable for us, therefore I tried to implement new option to skip files/elements with no comments. Feel free to review and request changes if needed.

#### Breaking
- None

#### Enhancements
- Option to skip elements with no comments

#### Bug Fixes
- None

### CODE REVIEW

**Comment by eneko** [comment]
This seems useful, thanks for putting the work to implement it!

**Comment by ncharniauski** [comment]
Could this be merged?

**Comment by leszek-s** [comment]
@eneko Do you plan to merge this?

**Comment by eneko** [comment]
Sorry, haven't tested this yet. How is this intended to work? If a file contains comments in some methods, types, but not in others, will documentation be generated for all methods/types on that file?

**Comment by Fiser33** [comment]
Only methods/properties with a documentation will be listed in generated file. If there is nothing documented in type (either top level or on method/property), no file is generated at all.

The only exception is enum, where cases do not get skipped if file is generated.

S pozdravem 
Mgr. Jakub Fišer

**Comment by leszek-s** [comment]
Great that it was merged. I hope a new version with this will also be released soon.

**Comment by jcabreram** [comment]
@eneko When will you be releasing a new version with this change? The README.md file has the usage option for `--skip-empty` listed already, but it's not available in the latest version (2.0.1). Thank you very much!

**Pull request merged**
